// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/block_worker.proto

package alluxio.grpc;

public interface KylinDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.block.KylinDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 state = 1;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>optional int32 state = 1;</code>
   * @return The state.
   */
  int getState();
}
