// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/block_worker.proto

package alluxio.grpc;

/**
 * <pre>
 * next available id: 2
 * </pre>
 *
 * Protobuf type {@code alluxio.grpc.block.KylinDataRequest}
 */
public  final class KylinDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alluxio.grpc.block.KylinDataRequest)
    KylinDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KylinDataRequest.newBuilder() to construct.
  private KylinDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KylinDataRequest() {
    dataId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new KylinDataRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KylinDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              dataId_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            dataId_.add(bs);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        dataId_ = dataId_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BlockWorkerProto.internal_static_alluxio_grpc_block_KylinDataRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BlockWorkerProto.internal_static_alluxio_grpc_block_KylinDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            KylinDataRequest.class, Builder.class);
  }

  public static final int DATAID_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList dataId_;
  /**
   * <code>repeated string dataId = 1;</code>
   * @return A list containing the dataId.
   */
  public com.google.protobuf.ProtocolStringList
      getDataIdList() {
    return dataId_;
  }
  /**
   * <code>repeated string dataId = 1;</code>
   * @return The count of dataId.
   */
  public int getDataIdCount() {
    return dataId_.size();
  }
  /**
   * <code>repeated string dataId = 1;</code>
   * @param index The index of the element to return.
   * @return The dataId at the given index.
   */
  public String getDataId(int index) {
    return dataId_.get(index);
  }
  /**
   * <code>repeated string dataId = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the dataId at the given index.
   */
  public com.google.protobuf.ByteString
      getDataIdBytes(int index) {
    return dataId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dataId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataId_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < dataId_.size(); i++) {
        dataSize += computeStringSizeNoTag(dataId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDataIdList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof KylinDataRequest)) {
      return super.equals(obj);
    }
    KylinDataRequest other = (KylinDataRequest) obj;

    if (!getDataIdList()
        .equals(other.getDataIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDataIdCount() > 0) {
      hash = (37 * hash) + DATAID_FIELD_NUMBER;
      hash = (53 * hash) + getDataIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static KylinDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KylinDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KylinDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KylinDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KylinDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KylinDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KylinDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static KylinDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static KylinDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static KylinDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static KylinDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static KylinDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(KylinDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * next available id: 2
   * </pre>
   *
   * Protobuf type {@code alluxio.grpc.block.KylinDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alluxio.grpc.block.KylinDataRequest)
      alluxio.grpc.KylinDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BlockWorkerProto.internal_static_alluxio_grpc_block_KylinDataRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BlockWorkerProto.internal_static_alluxio_grpc_block_KylinDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KylinDataRequest.class, Builder.class);
    }

    // Construct using alluxio.grpc.KylinDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      dataId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BlockWorkerProto.internal_static_alluxio_grpc_block_KylinDataRequest_descriptor;
    }

    @Override
    public KylinDataRequest getDefaultInstanceForType() {
      return KylinDataRequest.getDefaultInstance();
    }

    @Override
    public KylinDataRequest build() {
      KylinDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public KylinDataRequest buildPartial() {
      KylinDataRequest result = new KylinDataRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        dataId_ = dataId_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.dataId_ = dataId_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof KylinDataRequest) {
        return mergeFrom((KylinDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(KylinDataRequest other) {
      if (other == KylinDataRequest.getDefaultInstance()) return this;
      if (!other.dataId_.isEmpty()) {
        if (dataId_.isEmpty()) {
          dataId_ = other.dataId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureDataIdIsMutable();
          dataId_.addAll(other.dataId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      KylinDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (KylinDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList dataId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDataIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        dataId_ = new com.google.protobuf.LazyStringArrayList(dataId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @return A list containing the dataId.
     */
    public com.google.protobuf.ProtocolStringList
        getDataIdList() {
      return dataId_.getUnmodifiableView();
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @return The count of dataId.
     */
    public int getDataIdCount() {
      return dataId_.size();
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @param index The index of the element to return.
     * @return The dataId at the given index.
     */
    public String getDataId(int index) {
      return dataId_.get(index);
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the dataId at the given index.
     */
    public com.google.protobuf.ByteString
        getDataIdBytes(int index) {
      return dataId_.getByteString(index);
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @param index The index to set the value at.
     * @param value The dataId to set.
     * @return This builder for chaining.
     */
    public Builder setDataId(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIdIsMutable();
      dataId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @param value The dataId to add.
     * @return This builder for chaining.
     */
    public Builder addDataId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIdIsMutable();
      dataId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @param values The dataId to add.
     * @return This builder for chaining.
     */
    public Builder addAllDataId(
        Iterable<String> values) {
      ensureDataIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, dataId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataId() {
      dataId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string dataId = 1;</code>
     * @param value The bytes of the dataId to add.
     * @return This builder for chaining.
     */
    public Builder addDataIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIdIsMutable();
      dataId_.add(value);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alluxio.grpc.block.KylinDataRequest)
  }

  // @@protoc_insertion_point(class_scope:alluxio.grpc.block.KylinDataRequest)
  private static final KylinDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new KylinDataRequest();
  }

  public static KylinDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @Deprecated public static final com.google.protobuf.Parser<KylinDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<KylinDataRequest>() {
    @Override
    public KylinDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KylinDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KylinDataRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<KylinDataRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public KylinDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

