// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/block_worker.proto

package alluxio.grpc;

public interface KylinDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.block.KylinDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string dataId = 1;</code>
   * @return A list containing the dataId.
   */
  java.util.List<String>
      getDataIdList();
  /**
   * <code>repeated string dataId = 1;</code>
   * @return The count of dataId.
   */
  int getDataIdCount();
  /**
   * <code>repeated string dataId = 1;</code>
   * @param index The index of the element to return.
   * @return The dataId at the given index.
   */
  String getDataId(int index);
  /**
   * <code>repeated string dataId = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the dataId at the given index.
   */
  com.google.protobuf.ByteString
      getDataIdBytes(int index);
}
